import "server-only";
import manifest from "./photoManifest.generated.json";
import { CATEGORY_META, SIGNATURE_STORY_COPY, type Photo, type PortfolioCategory, type PortfolioCategorySlug } from "./photos";

/**
 * Reads the photo manifest generated by scripts/generate-photo-manifest.mjs,
 * which runs as a plain Node script before `next build` (see the
 * "prebuild"/"predev" scripts in package.json) and scans /public/photos/**.
 *
 * Publishing a new photograph is "add the file to the right folder and
 * redeploy" — no code change required. See that script's header comment
 * for the folder → section map, ordering rules, "cover.*" convention, and
 * alt-text generation.
 */

type Manifest = {
  hero: Photo[];
  categories: Record<PortfolioCategorySlug, Photo[]>;
  story: Photo[];
  about: Photo | null;
  testimonials: Photo[];
  recent: Photo[];
};

const data = manifest as unknown as Manifest;

export function getCategory(slug: string): PortfolioCategory | undefined {
  const meta = CATEGORY_META[slug as PortfolioCategorySlug];
  const photos = data.categories[slug as PortfolioCategorySlug];
  if (!meta || !photos) return undefined;
  return { slug: slug as PortfolioCategorySlug, ...meta, photos };
}

export function getPortfolioCategories(): PortfolioCategory[] {
  return (Object.keys(CATEGORY_META) as PortfolioCategorySlug[]).map(
    (slug) => getCategory(slug) as PortfolioCategory
  );
}

export function getHeroSlides(): Photo[] {
  return data.hero;
}

export function getSignatureStory(): { heading: string; intro: string; photos: Photo[] } {
  return { ...SIGNATURE_STORY_COPY, photos: data.story };
}

export function getAboutPortrait(): Photo | null {
  return data.about;
}

export function getTestimonialBackgrounds(): Photo[] {
  return data.testimonials;
}

export function getRecentStories(): Photo[] {
  return data.recent;
}
